### ISSUE TITLE
Requires ext-Fileinfo, please declare it

### ISSUE THREAD

**Issue by tpraxl** [elvetemedve/behat-screenshot#13]
Given 
* your project uses `"bex/behat-screenshot": "^1.2"`
* And your php installation doesn't have the extension `php_fileinfo` installed (php.ini)

When
* you run `bin\behat`

Then an error will be thrown:
```
PHP Fatal error:  Uncaught Error: Class 'finfo' not found in {project-root}\vendor\bex\behat-screenshot\src\Bex\Behat\ScreenshotExtens
ion\Driver\Local.php:48
Stack trace:
#0 {project-root}\vendor\bex\behat-extension-driver-lo
cator\src\Bex\Behat\ExtensionDriverLocator\DriverLocator.php(98): Bex\Behat\Scre
enshotExtension\Driver\Local->__construct()
#1 {project-root}\vendor\bex\behat-extension-driver-lo
cator\src\Bex\Behat\ExtensionDriverLocator\DriverLocator.php(54): Bex\Behat\Exte
nsionDriverLocator\DriverLocator->createDrivers(Array)
#2 {project-root}\vendor\bex\behat-screenshot\src\Bex\
Behat\ScreenshotExtension\ServiceContainer\Config.php(119): Bex\Behat\ExtensionD
riverLocator\DriverLocator->findDrivers(Object(Symfony\Component\DependencyInjec
tion\ContainerBuilder), Array, Array)
#3 {project-root}\vendor\bex\behat-screenshot\src\Bex\
Behat\ScreenshotExtension\ServiceContainer\ScreenshotExtension.php(8 in {project-root}\vendor\bex\behat-screenshot\src\Bex\Behat\Scree
nshotExtension\Driver\Local.php on line 48
```

I suggest that you either work around the finfo requirement or you declare the requirement in `composer.json`:
```
"require": {
    "php": ">=5.4",
    "behat/behat": "^3.0.0",
    "behat/mink-extension": "^2.0.0",
    "bex/behat-extension-driver-locator": "^1.0.2",
    "symfony/filesystem": "^2.7|^3.0",
    "symfony/finder": "^2.7|^3.0",
    "ext-Fileinfo": "*"
},
```
I'll post a pull request with the patch in a moment.

**Comment by tkotosz** [comment]
Thanks you for your report and contribution. The finfo only used for the "clear_screenshot_directory" feature, so it is not required by the extension if this feature is disabled.

So we will review the code and we will:
1. use something else instead of finfo to remove this requirement or
2. amend the code to only use finfo if this feture is enabled and will also add an extra validation to the configuration, so if anybody enables the clear_screenshot_directory fetaure then behat will throw a configuration error if finfo is not available.

**Comment by tpraxl** [comment]
That sounds great. Thanks:)

**Comment by tkotosz** [comment]
It seems we didn't run into this issue because the extra php_fileinfo.dll only required for windows users: http://php.net/manual/en/fileinfo.installation.php

**Comment by elvetemedve** [comment]
Fix is released in https://github.com/elvetemedve/behat-screenshot/releases/tag/1.2.1
