### ISSUE TITLE
complains about null parameter when using @beforeStep in feature context

### ISSUE THREAD

**Issue by tpraxl** [elvetemedve/behat-screenshot#15]
I just noticed that – if you annotate a method with `@beforeStep` in your `FeatureContext extends MinkContext` and you're using behat-screenshot – behat-screenshot complains about a null parameter, when starting bin/behat:

```
  [Behat\Testwork\Call\Exception\CallErrorException]
  Warning: end() expects parameter 1 to be array, null given in {projectRoot}\vendor\bex\behat-screenshot\src\Bex\Behat\ScreenshotExtension\Service\ScreenshotTaker.php line 91

behat [-s|--suite SUITE] [-f|--format FORMAT] [-o|--out OUT] [--format-settings
FORMAT-SETTINGS] [--init] [--lang LANG] [--name NAME] [--tags TAGS] [--role ROLE
] [--story-syntax] [-d|--definitions DEFINITIONS] [--append-snippets] [--no-snip
pets] [--strict] [--order ORDER] [--rerun] [--stop-on-failure] [--dry-run] [--]
[<paths>]
```
I originally wanted to initiate a debug-session for behat with that method. But even an empty method causes this error:

in `features/bootstrap/FeatureConetxt.php`:
```
 /**
    * @beforeStep
    *
    * @param BeforeStepScope $scope
    */
   public function synchronizeClientSession(BeforeStepScope $scope)
   {
   }
```

As soon as I remove the annotation `@beforeStep` everything works again – no complaints.

**Comment by tkotosz** [comment]
we recently changed the screenshot listener, so maybe there is a bug in it. But based on the error this method is called: https://github.com/elvetemedve/behat-screenshot/blob/master/src/Bex/Behat/ScreenshotExtension/Listener/ScreenshotListener.php#L90
which should be called only after a scenario tested, so this is a weird issue.
Anyway what I can see:
1. here the screenshot array should be initialized: https://github.com/elvetemedve/behat-screenshot/blob/master/src/Bex/Behat/ScreenshotExtension/Service/ScreenshotTaker.php#L38 , so a `$this->screenshots = [];` is missing from the constructor.
2. and here: https://github.com/elvetemedve/behat-screenshot/blob/master/src/Bex/Behat/ScreenshotExtension/Listener/ScreenshotListener.php#L95
and extra check required to see if there is any image, so something like this:
```
        if ($this->shouldSaveScreenshot($event)) {
            $fileName = $this->filenameGenerator->generateFileName($event->getFeature(), $event->getScenario());
            $image = $this->screenshotTaker->getImage();
            if ($image) {
                $this->screenshotUploader->upload($image, $fileName);
            }
        }
```
Could you please check that if it is working as expected if you made these modifications in the extension?

**Comment by tpraxl** [comment]
I changed https://github.com/elvetemedve/behat-screenshot/blob/master/src/Bex/Behat/ScreenshotExtension/Service/ScreenshotTaker.php#L42 and added `$this->screenshots = [];` not without noticing that  https://github.com/elvetemedve/behat-screenshot/blob/master/src/Bex/Behat/ScreenshotExtension/Service/ScreenshotTaker.php#L51 fetches the screenshots from the mink session. So I think this is not what we should do.

Running `bin/behat` with that change causes the following output
```
$ bin/behat
      Screenshot has been taken. Open image at ./reports/screenshots\features_fo
rm-client-validation_feature_6.png
      Screenshot has been taken. Open image at ./reports/screenshots\features_fo
rm-client-validation_feature_11.png
      Screenshot has been taken. Open image at ./reports/screenshots\features_fo
rm-client-validation_feature_16.png
      Screenshot has been taken. Open image at ./reports/screenshots\features_fo
rm-field-completeness_feature_6.png
      Screenshot has been taken. Open image at ./reports/screenshots\features_fo
rm-field-rendering_feature_6.png
      Screenshot has been taken. Open image at ./reports/screenshots\features_fo
rm-receive-data_feature_6.png
      Screenshot has been taken. Open image at ./reports/screenshots\features_fo
rm-receive-data_feature_13.png
      Screenshot has been taken. Open image at ./reports/screenshots\features_fo
rm-server-validation_feature_7.png
      Screenshot has been taken. Open image at ./reports/screenshots\features_fo
rm-server-validation_feature_14.png
      Screenshot has been taken. Open image at ./reports/screenshots\features_fo
rm-server-validation_feature_21.png
```
along with 0 byte screenshot files in the reports directory. When I turn off `@beforeStep` there's just a single screenshot taken, because there's just one assertion fail.

Without knowing your code too well, I think I should do something like initializing the screenshot array in the mink-session..

**Comment by tkotosz** [comment]
@tpraxl did you do the 2nd thing as well which I mentioned? (the extra check to the listener)

**Comment by tpraxl** [comment]
When I perform both suggested changes, behat wouldn't complain anymore, but it wouldn't run either. I think that `@beforeStep` somehow prevents an important initialization step. Notice: When I remove `@beforeStep` everything runs fine, even after the suggested changes.

**Comment by tkotosz** [comment]
> behat wouldn't complain anymore, but it wouldn't run either
wow, it is really weird. Could you please tell me these?
- behat version
- mink-extension version
- behat-screenshot extension version

I will do some debugging today.

**Comment by tpraxl** [comment]
Hi,

thanks a lot!
I would have set up a test project for you, but currently I have absolutely no time. So this is what I can offer right now. Maybe later today:

```
"require-dev": {
        "behat/behat": "~3.0",
        "behat/mink": "~1.5",
        "behat/mink-extension": "~2.2",
        "behat/mink-goutte-driver": "~1.0",
        "behat/mink-selenium2-driver": "~1.1",
        "instaclick/php-webdriver":"~1.0",
        "phpunit/phpunit":"~5.3",
        "emuse/behat-html-formatter": "dev-master",
        "bex/behat-screenshot": "^1.2"
    },
```
php version: 7.0.5, running on Windows 8.1, cygwin, using selenium-server-standalone-2.53.0.jar

```
class FeatureContext extends MinkContext
{   
//...
/**
    * @beforeStep
    *
    * @param BeforeStepScope $scope
    */
   public function synchronizeClientSession(BeforeStepScope $scope)
   {
   }
//...
}

**Comment by tpraxl** [comment]
Ah.. and just in case, behat.yml (with the server set up like this: `php -S localhost:1234 -t {yourdocroot}`)
```
# behat.yml
default:
 autoload:
     '': %paths.base%/features/bootstrap
 formatters: 
    html:
      output_path: %paths.base%/reports
 extensions:
  Behat\MinkExtension:
   base_url:  'http://localhost:1234'
   default_session: selenium2
   browser_name: 'firefox'
   goutte:    ~
   selenium2:
    wd_host: "http://127.0.0.1:4444/wd/hub"
  emuse\BehatHTMLFormatter\BehatHTMLFormatterExtension:
      name: html
      renderer: Twig,Behat2
      file_name: Index
      print_args: true
      print_outp: true
      loop_break: true
  Bex\Behat\ScreenshotExtension:
      image_drivers:
           local:
               screenshot_directory: ./reports/screenshots
```

**Comment by tkotosz** [comment]
Thanks, 
Also could you please explain what do you mean by the "it wouldn't run either"? Is behat stops without running any scenarios? Or just the extension doesn't take a screenshot even when it should?
I have tried to reproduce the issue but I only run into the `Warning: end() expects parameter...` error when I have missed the use statement in the FeatureContext related to the BeforeStepScope. (in this case I got an error related to the wrong parameter for the beforeStep method and one error from the extension related to the empty screenshots internal variable)

**Comment by tkotosz** [comment]
@tpraxl So could you please make sure you didn't miss the use statement for the `BeforeStepScope` (`Behat\Behat\Hook\Scope\BeforeStepScope`) in your `FeatureContext`? This is the only way how I was able to reproduce the `Warning: end() expects parameter 1 to be array, null given` error.

**Comment by tpraxl** [comment]
> Also could you please explain what do you mean by the "it wouldn't run either"? Is behat stops without running any scenarios?
This means: I have applied the suggested code changes. After that, `behat/run` would simply return. No action taken, no error message. No screenshot.

**Comment by tpraxl** [comment]
Oh.. well. I'm feeling very sorry. I didn't apply the use-statement!.. That's it. When I `use Behat\Behat\Hook\Scope\BeforeStepScope;` It just works. I'm very sorry for making you spend so much effort on this. Thanks for your help.

**Comment by tkotosz** [comment]
Haha no problem. But it is weird. Behat should show the error exception / fatal error which was thrown because of the missing use statement. Anyway I happy this solved the problem. I will make a pr about the changes which you applied to the extension.

**Comment by tpraxl** [comment]
Thank you very much!
