### ISSUE TITLE
Check the driver to not create warnings

### ISSUE THREAD

**Issue by lologhi** [elvetemedve/behat-screenshot#19]
Hi!
Adding a `if (!$driver instanceof Selenium2Driver) { return }` could prevent this extension to try to create screenshot while using the Symfony2 driver, for example.
Thx !

**Comment by elvetemedve** [comment]
@lologhi A fix has been released as version [1.2.3](https://github.com/elvetemedve/behat-screenshot/releases/tag/1.2.3).

**Comment by lologhi** [comment]
So fast !! Thanks a lot !!
