### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by andreiashu** [elvetemedve/behat-screenshot#31]
I really like this extension. The problem is that as the tests run the extension keeps adding screenshots to the array of screenshots (in ScreenshotTaker->takeScreenshot() which in itself is a memory leak.

With this extension disabled we don't run into memory leaks:

```
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 8912975 bytes) in [...]
```

**Comment by tkotosz** [comment]
We introduced this change in the 1.2.0 version if I remember correctly, to be able to capture not just the screenshot of the failing step but the whole scenario if that configured in the behat.yml.
We will look into this memory leak issue and will let you know if we manage to fix it. (at least we need to fix the code to do this only if the screenshot_taking_mode is not just the default "failed_step")

**Comment by tkotosz** [comment]
@andreiashu Sorry for the long delay I just created a pr with a possible fix for the issue: It will take screenshot only about the failed steps by default and will only take screenshot about the other steps if the `screenshot_taking_mode` is `failed_scenarios` or `all_scenarios`.

**Comment by elvetemedve** [comment]
@andreiashu Could you please test the latest version [1.2.6](https://github.com/elvetemedve/behat-screenshot/releases/tag/1.2.6)? It should not take unnecessary screenshots anymore in **failed_steps** mode.
