### ISSUE TITLE
Extension not working with behat 3.1.0

### ISSUE THREAD

**Issue by ellahikamran** [elvetemedve/behat-screenshot#36]
the extension is not working this is what my composer file looks like
`{
  "name": "project",
  "description": "",
  "type": "project",
  "license": "MIT",
  "authors": [
    {
      "name": "PROJECT",
      "role": "Dev team"
    }
  ],
  "require": {
    "behat/mink": "*",
    "behat/mink-goutte-driver": "~1.2",
    "jcalderonzumba/gastonjs": "~1.0.2",
    "jcalderonzumba/mink-phantomjs-driver": "~0.3.1",
    "phpunit/phpunit": "4.8.*",
    "symfony/css-selector": "~2.8",
    "bex/behat-screenshot": "1.2.*"
  },
  "minimum-stability": "dev",
  "prefer-stable": true
}`

behat.yml file 
`default:
  suites:
    default:
      contexts:
        - FeatureContext
  extensions:
    Behat\MinkExtension:
      goutte: ~
      selenium2: ~
      base_url: http://mysite.com
    Bex\Behat\ScreenshotExtension:
      image_drivers:
        local:
          screenshot_directory: '/var/www/behat/results/screenshot'
test:
  suites:
    default:
      filters:
        tags: "@test"`
Can you let me know what am i missing .

**Comment by tkotosz** [comment]
Hi,

The `goutte` driver doesn't support taking screenshot. If you use `selenum2` instead then it should work correctly.

**Comment by tkotosz** [comment]
Working test project with selenium2+phantomjs: https://github.com/tkotosz/behat-test-project-with-phantomjs
