### ISSUE TITLE
Add option to change screenshots repository

### ISSUE THREAD

**Issue by vincentmary** [elvetemedve/behat-screenshot#41]
Hello, 

 I'm working on a behat project where i'd like to separate test suites on my jenkins instance into different jobs. To avoid jobB erasing screenshots from jobB I thought that it will be nice to add the possibility of extending screenshot repository defined in .yml file. That way my jobs will generate their screenshots in their own folder rather than using the one in .yml. 

 I'd like to have you opinion on it, and if you're thinking it's  a good idea, I'd be glad to work on that and submit a PR. 

Best regards

**Comment by elvetemedve** [comment]
Hi @vincentmary, 

I don't think it needs code changes. Basically you have two options:

1. Turn off wiping the screenshot directory from Yaml, by `clear_screenshot_directory: false`.
1. You can define a [Behat profile](http://behat.org/en/latest/user_guide/configuration.html) for each test suite where you would set different screenshot directory per profile.

Could any of these work for you?

**Comment by vincentmary** [comment]
Hello @elvetemedve, thanks  for the reply, 

 Solution 1 was not a good solution for me, because I like the fact that screenshots were always the result of last build. With clear_screenshot_directory to false, we will have previous test failures.

 I didn't think for solution 2. I used to consider profile as different platforms where my application could  be, not to handle different suites. But it can work so I will look forward to using it. 

Thank you very much @elvetemedve  and have a nice day!
